generate:
  client: true
model:
  package: gqlclient
  filename: models_gen.go # https://github.com/99designs/gqlgen/tree/master/plugin/modelgen
client:
  package: gqlclient
  filename: client.go # Where should any generated client go?
models:
  Int:
    model: github.com/99designs/gqlgen/graphql.Int64
  Date:
    model: github.com/99designs/gqlgen/graphql.Time
  ID:
    model: github.com/99designs/gqlgen/graphql.ID
  String:
    model: github.com/99designs/gqlgen/graphql.String
  UploadOrUrl:
    model: github.com/99designs/gqlgen/graphql.String
schema:
  - "schema/*.graphql"
query:
  - "graph/*.graphql" # Where are all the query files located?
